---
- name: Install Apache on EC2
  hosts: terra
  become: true
  tasks:
    - name: Update package cache
      yum:
        name: "*"
        state: latest
      become: yes
      # Now we install apache

    - name: Install Apache
      yum:
        name: httpd
        state: present
      become: yes

    - name: Start Apache service
      service:
        name: httpd
        state: started
        enabled: yes
      become: yes

